import { introduction } from './modules/introduction';

export const courses = [
	{
		id: 1,
		name: 'Master en Programación Web',
		link: '#/course/1',
		price: 6000,
		teacher: 'Isabel María ',
		teacherOccupation: 'Professor',
		image: 'assets/images/courses/master.jpg',
		teacherPhoto: 'assets/images/team/person1.jpg',
		description:
			'Obtendrás una formación completa y adaptada a las necesidades demandadas por el mercado laboral actual. Utilizarás una metodología eminentemente práctica con un proyecto de desarrollo que será tu carta de presentación ante las empresas.',
		completeInfo: introduction?.info,
		modules: [introduction],
	},
	{
		id: 2,
		name: 'Diplomado en Programación Web',
		link: '#/course/2',
		price: 5000,
		teacher: 'Sergio Segura ',
		teacherOccupation: 'Professor',
		image: 'assets/images/courses/diplo.jpg',
		teacherPhoto: 'assets/images/team/person8.jpg',
		description:
			'El Diplomado en programación Web tiene como objetivo formar profesionales integrales en el área de desarrollo web, capaces de manejar las tecnologías más actuales y utilizando las más avanzadas técnicas del sector.',
		completeInfo: introduction?.info,
		modules: [introduction],
	},
	{
		id: 3,
		name: 'Postgrado en Programación Web',
		link: '#/course/3',
		price: 4000,
		teacher: 'Andrés González',
		teacherOccupation: 'Assistant',
		image: 'assets/images/courses/postgrado.jpg',
		teacherPhoto: 'assets/images/team/person3.jpg',
		description:
			'El posgrado en Desarrollo y Programación Web busca crear profesionales altamente capacitados para entrar en al campo laboral, desarrollando desde cero sitios web de alta calidad.',
		completeInfo: introduction?.info,
		modules: [introduction],
	},
	{
		id: 4,
		name: 'Curso Front-End',
		link: '#/course/4',
		price: 3000,
		teacher: 'Liset Bichili ',
		teacherOccupation: 'Teacher',
		image: 'assets/images/courses/master1.jpg',
		teacherPhoto: 'assets/images/team/person2.jpg',
		description:
			'Ser el responsable del aspecto de las aplicaciones y las funcionalidades con las cuales interactúa el usuario es un gran reto, nosotros te ayudamos a que lo tengas bajo control.',
		completeInfo: introduction?.info,
		modules: [introduction],
	},
	{
		id: 5,
		name: 'Curso Back-End',
		link: '#/course/5',
		price: 2500,
		teacher: 'Gregorio Lombardo',
		teacherOccupation: 'Teacher',
		image: 'assets/images/courses/front.png',
		divClass: 'review_singel',
		teacherPhoto: 'assets/images/team/person5.jpg',
		description:
			'Procesar datos recopilados en una interfaz, gestionar bases de datos, etc. son funciones propias del Back-End, es decir, del cerebro dentro de un proyecto web. ¿Quieres ser la pieza clave dentro del desarrollo web?',
		completeInfo: introduction?.info,
		modules: [introduction],
	},
	{
		id: 6,
		name: 'Curso Full Stack',
		link: '#/course/6',
		price: 4500,
		teacher: 'Daniel Fernández ',
		teacherOccupation: 'Teacher',
		image: 'assets/images/courses/backend.jpg',
		divClass: 'review_singel',
		teacherPhoto: 'assets/images/team/person7.jpg',
		description:
			'Deseas convertirte en un desarrollador web capaz de crear productos digitales para internet de principio a fin, con el curso Full Stack estás a un paso de lograrlo.',
		completeInfo: introduction?.info,
		modules: [introduction],
	},
];
