export const events = [
	{
		id: 1,
		name: 'Master en Programación Web',
		day: 10,
		month: 'Octubre ',
		image: 'master.jpg',
		detail: 'asdasd',
		description: '',
	},
	{
		id: 2,
		name: 'Diplomado en Programación Web',
		day: 10,
		month: 'Octubre ',
		image: 'master.jpg',
		detail: 'asdasd',
		description: '',
	},
	{
		id: 3,
		name: 'Postgrado en Programación Web',
		day: 10,
		month: 'Octubre ',
		image: 'postgrade.jpg',
		detail: 'asdasd',
		description: '',
	},
	{
		id: 4,
		name: 'Curso Front-End',
		day: 10,
		month: 'Octubre ',
		image: 'front-end.jpg',
		detail: 'asdasd',
		description: '',
	},
	{
		id: 5,
		name: 'Curso Back-End',
		day: 10,
		month: 'Octubre ',
		image: 'back-end.jpg',
		detail: 'asdasd',
		description: '',
	},
	{
		id: 6,
		name: 'Curso Full Stack',
		day: 10,
		month: 'Octubre ',
		image: 'full-stack.jpg',
		detail: 'asdasd',
		description: '',
	},
];
